# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    permissions:
      packages: write
      contents: write
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: inno-setup-download
      uses: pwall2222/inno-setup-download@v0.0.6

    - name: Build Windows Installer
      working-directory: ./OmegaStrikersModLoader
      run: ./buildInstaller.bat

    - name: Zip output
      uses: TheDoctor0/zip-release@0.7.6
      with: 
        filename: portable.zip
        directory: ./OmegaStrikersModLoader/bin/Release/net8.0/
        
    - name: Zip installer
      uses: TheDoctor0/zip-release@0.7.6
      with: 
        filename: windows-installer.zip
        directory: ./Output/
        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./OmegaStrikersModLoader/bin/Release/net8.0/portable.zip
          ./Output/windows-installer.zip
          ./Output/OmegaStrikersModInstallerSetup.exe
    

        
    
    
